export type PortfolioItem = {
  id: number;
  name: string;
  title: string;
  date: string;
  description: string;
  images: string[];
  videos?: string[];
};

export type PortfolioDataProps = {
  [project: string]: PortfolioItem;
};

export const portfolioData: PortfolioDataProps = {
  integration: {
    id: 1,
    name: "intergration",
    title: "Integration",
    date: "2020-01-01",
    description: "This is project 1",
    images: [
      "1a.jpg",
      "1b.jpg",
      "1c.jpg",
      "1d.jpg",
      "1e.jpg",
      "1f.jpg",
      "1g.jpg",
      "1h.jpg",
      "1i.jpg",
      "1j.jpg",
      "1k.jpg",
      "1l.jpg",
      "1m.jpg",
      "1n.jpg",
      "1o.jpg",
    ],
    videos: [],
  },
  internship: {
    id: 2,
    name: "internship",
    title: "Project 2",
    date: "2020-01-01",
    description: "This is project 2",
    images: ["2a.jpg", "2b.jpg", "2c.jpg", "2d.jpg", "2e.jpg", "2f.jpg"],
    videos: [],
  },
  complexity: {
    id: 3,
    name: "complexity",
    title: "Project 3",
    date: "2020-01-01",
    description: "This is project 3",
    images: ["3a.jpg", "3b.jpg", "3c.jpg", "3d.jpg", "3e.jpg", "3f.jpg"],
  },
  rxm: {
    id: 4,
    name: "rxm",
    title: "Project 4",
    date: "2020-01-01",
    description: "This is project 4",
    images: [
      "4a.jpg",
      "4b.jpg",
      "4c.jpg",
      "4d.jpg",
      "4e.jpg",
      "4f.jpg",
      "4g.jpg",
      "4h.jpg",
      "4i.jpg",
    ],
  },
  industryAndPractice: {
    id: 5,
    name: "industryAndPractice",
    title: "Project 5",
    date: "2020-01-01",
    description: "This is project 5",
    images: [
      "5a.jpg",
      "5b.jpg",
      "5c.jpg",
      "5d.jpg",
      "5e.jpg",
      "5f.jpg",
      "5g.jpg",
      "5h.jpg",
      "5i.jpg",
      "5j.jpg",
      "5k.jpg",
      "5l.jpg",
      "5m.jpg",
      "5n.jpg",
      "5o.jpg",
      "5p.jpg",
    ],
  },
  danceStudio: {
    id: 6,
    name: "danceStudio",
    title: "Project 6",
    date: "2020-01-01",
    description: "This is project 6",
    images: [
      "6a.jpg",
      "6b.jpg",
      "6c.jpg",
      "6d.jpg",
      "6e.jpg",
      "6f.jpg",
      "6g.jpg",
      "6h.jpg",
      "6i.jpg",
      "6j.jpg",
      "6k.jpg",
      "6l.jpg",
      "6m.jpg",
      "6n.jpg",
    ],
  },
  blackHistory: {
    id: 7,
    name: "blackHistory",
    title: "Project 7",
    date: "2020-01-01",
    description: "This is project 7",
    images: [
      "7a.jpg",
      "7b.jpg",
      "7c.jpg",
      "7d.jpg",
      "7e.jpg",
      "7f.jpg",
      "7g.jpg",
      "7h.jpg",
      "7i.jpg",
      "7j.jpg",
      "7k.jpg",
      "7l.jpg",
      "7m.jpg",
    ],
  },
  vc: {
    id: 8,
    name: "vc",
    title: "Project 8",
    date: "2020-01-01",
    description: "This is project 8",
    images: ["8a.jpg", "8b.jpg", "8c.jpg", "8d.jpg"],
  },
  cardStructure: {
    id: 9,
    name: "cardStructure",
    title: "Card Structure",
    date: "2020-01-01",
    description:
      "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odit accusamus eaque quasi tempore molestiae nobis possimus repellendus dolorem quaerat voluptates enim beatae ut sunt suscipit architecto, rem nulla tempora cum.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odit accusamus eaque quasi tempore molestiae nobis possimus repellendus dolorem quaerat voluptates enim beatae ut sunt suscipit architecto, rem nulla tempora cum.",
    images: [
      "9a.jpg",
      "9b.jpg",
      "9c.jpg",
      "9d.jpg",
      "9e.jpg",
      "9f.jpg",
      "9g.jpg",
      "9h.jpg",
      "9i.jpg",
      "9j.jpg",
      "9k.jpg",
      "9m.jpeg",
      "9n.jpeg",
    ],
    videos: ["9l.mp4"],
  },
  epq: {
    id: 10,
    name: "epq",
    title: "Project 10",
    date: "2020-01-01",
    description: "This is project 10",
    images: [
      "10a.jpeg",
      "10b.jpg",
      "10c.jpg",
      "10d.JPG",
      "10e.JPG",
      "10f.JPG",
      "10g.JPG",
      "10h.PNG",
      "10i.jpg",
    ],
  },
};
// comment!!!!!
